# Generated by Django 5.1.6 on 2025-04-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False, max_length=55),
        ),
    ]
